version: '2.17.2'

services:
    postgres : 
      image: postgres # hub.docker.com
      ports :
        - "5433:5432"
      restart : always
      environment : 
        DB_USERNAME: postgres
        DB_PASSWORD: ztlab101
        DB_NAME: job
        DB_HOST: localhost
